# Site settings
title:            "The Law Office of Thomas G. Morin, PLLC"
description:      ""
url:              ""
google_analytics: false

# Where things are
destination:      ./_site

# Handling Reading
exclude:          ["Gemfile", "Gemfile.lock", "README.md", ".gitignore"]

# Assets
sass:
    style:        compressed

sass:
    sass_dir:     ui/css

# Conversion
markdown:         kramdown

# Outputting
permalink:        /:categories/:year/:month/:title/

excerpt_separator: <!--more-->

# Compensating for gh-pages project site
# https://github.com/jekyll/jekyll/issues/332
# baseurl:          /morin-legal
baseurl:          ""

plugins:
  - jekyll-redirect-from

collections:
  practice-areas:
    order:
      - estate-planning.md
      - probating-estate.md
      - business-planning.md
